project:
  type: book

book:
  title: "Clase_20_09"
  author: "Irasema Pedroza"
  date: "20/9/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - Apendice.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



